# Generated by Django 4.1.3 on 2023-12-14 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=255, null=True, verbose_name='Last Name')),
                ('organisation', models.CharField(max_length=255, null=True, verbose_name='Organisation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Team Name')),
                ('tableNumber', models.IntegerField(null=True, verbose_name='Table Number')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Venue Name')),
                ('floor', models.IntegerField(null=True, verbose_name='Floor')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Issue Title')),
                ('desc', models.CharField(max_length=255, null=True, verbose_name='Issue Description')),
                ('platform', models.CharField(max_length=255, null=True, verbose_name='Platform Information')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Accepted', 'Accepted')], default='Open', max_length=255, null=True, verbose_name='Status')),
                ('timeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('timeClosed', models.DateTimeField(auto_now_add=True, verbose_name='Closed Time')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mentor')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.venue'),
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=255, null=True, verbose_name='Team Name')),
                ('tableNumber', models.CharField(max_length=10, null=True, verbose_name='Table Number')),
                ('round', models.CharField(choices=[('Round 1', 'Round 1'), ('Round 2', 'Round 2'), ('Round 3', 'Round 3'), ('Round 4', 'Round 4')], max_length=255, null=True, verbose_name='Round')),
                ('criteriaA', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=255, null=True, verbose_name='Criteria A')),
                ('criteriaB', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=255, null=True, verbose_name='Criteria B')),
                ('criteriaC', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=255, null=True, verbose_name='Criteria C')),
                ('criteriaD', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=255, null=True, verbose_name='Criteria D')),
                ('timeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Time Created')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mentor')),
            ],
        ),
    ]
