# Generated by Django 4.1.3 on 2023-12-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='Email Address'),
        ),
    ]
