# Generated by Django 4.1.3 on 2023-12-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mentor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email Address'),
        ),
    ]
