# Generated by Django 4.1.3 on 2023-12-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mentor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='criteriaA',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=255, null=True, verbose_name='Innovation'),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='criteriaB',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=255, null=True, verbose_name='Feasibility'),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='criteriaC',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=255, null=True, verbose_name='Social Relevance'),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='criteriaD',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=255, null=True, verbose_name='Business Model'),
        ),
    ]
